language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov codecov
# command to run tests
script:
  - coverage run tests.py
  - pytest

after_success:
  - codecov