language: python
python:
- '3.6'
- '3.7'
- '3.8'
- 3.8-dev
install:
- pip install -r requirements.txt
- pip install pytest pytest-cov codecov coveralls imageio json-tricks
- pip install -e . -v
script:
- pytest ./test/unisens_test.py --cov=unisens/
after_success:
- coveralls
deploy:
  provider: pypi
  username: skjerns
  password:
    secure: r/rlw016CaiqXhqGus2IFmXFiJv2w1gKB56IZitKe210Fbc2MtbNubidwtKCxTtR+OfjGmSnWcuEGqS68TMQptRBEof2v1SIG8V5iMhF96qOSPUOvAW7ZEkZqMHgKTxEr15+JIRxI+EZYjQpKR5aFq69aBWqDK7r2U2UWvIf30JKXtP7e1MdSnj6VWbAgPJl6M4dhYoF3FE3IcpV8EdJnO3kBBUeHSC+m7VNuX9d5L55N4LN2yF3TuBYa4RDfaeYB0MmeLF0kNSq2jecmDwg1ZjenoOKj8l3e25EUWciHhWdbhwCu5GZjxmIsQJ8Wxdo/kRIuW6+PkQRI3zGGoqm46MiltCKea9g30gvexRwVHqxwmZT2pycWu3nyQt6KUwxVPZZ6byiAnK4NUI6Zrt4y4ID3lnjP0489t1XN5d66X+Tr0hKxrd1XnvN8fvIZFu6SVA90s9VPMyCbc2JM+FAh9YU6YMOUSNOMz1ESZRGZYF6z/+QKBhjp9LY6LYJ5ZARFqrujmWzhbDFaK6fYa6LRIJ010wHxqnrhG+MTBD1Ie+khKE5R8Bx7+iqlJp796Fi1J5ZAHmmwEPk1y7Sys5piQWhxH+GnwMKGtfJ5jFSFgoI8NHge4wtFiT/ap8ni4V+X5uzxDSe0bbeurU3P7INDibmurzYCAFKba197avnCB8=
  edge: true
  on:
    tags: true
