language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov codecov 
  - pip install -e . -v
# command to run tests
script:
  - pytest ./test/unisens_test.py
  - coverage run ./test/unisens_test.py

after_success:
  - codecov
  
deploy:
  provider: pypi
  user: "__token__"
  password: ...
  secure: "Your encrypted token"
  on:
    tags: true