# This workflow will install Python dependencies, run tests with Python versions 3.8 and 3.11

name: Testing

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest coverage # flake8
        pip install -r test-requirements.txt
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        coverage run -m pytest
        coverage report -m --skip-covered --include=./unisens/* --precision=2
    - name: Test with unittest
      run: |
        coverage run -m unittest discover -p '*_test.py'
        coverage report -m --skip-covered --include=./unisens/* --precision=2

